### ISSUE TITLE
`generate()` crashes on a fresh install: `semhash>=0.3.2` resolves to 0.4.x, whose `DeduplicationResult` API is incompatible

### ISSUE THREAD

**Issue by Faris-Abuali** [stair-lab/kg-gen#98]
# `generate()` crashes on a fresh install: `semhash>=0.3.2` resolves to 0.4.x, whose `DeduplicationResult` API is incompatible

## Summary

On a fresh install, the default `generate()` path crashes during SEMHASH
deduplication with:

```
AttributeError: 'DeduplicationResult' object has no attribute 'duplicates'
```

The root cause is the loose dependency pin **`semhash>=0.3.2`** in
`pyproject.toml`. pip resolves this to the latest **semhash 0.4.1**, but
`src/kg_gen/utils/deduplicate.py` is written against the **semhash 0.3.x**
`DeduplicationResult` API (`.selected`, `.duplicates`, `duplicate.record`,
`duplicate.duplicates[0][0]`), which 0.4.x reworked. Because SEMHASH is the
**default** `deduplication_method`, every new user hits this on their first call.

## Environment

- `kg-gen` 0.4.0 (installed via `pip install -e .` from `main`)
- `semhash` 0.4.1 (auto-resolved from `semhash>=0.3.2`)
- Python 3.13.12, Linux

## Steps to reproduce

```python
from kg_gen import KGGen
kg = KGGen(model="ollama/llama3.3:70b", api_base="https://...")  # any backend
kg.generate(input_data="Chlorophyll absorbs sunlight in the thylakoid membrane.")
# -> AttributeError during the default SEMHASH dedup step
```

Minimal, LLM-independent repro of the underlying API mismatch (on semhash 0.4.x):

```python
from semhash import SemHash
r = SemHash.from_records(records=["cat", "cats", "dog"]).self_deduplicate(threshold=0.9)
r.duplicates   # AttributeError on semhash 0.4.x (works on 0.3.x)
```

## Traceback (trimmed)

```
File ".../kg_gen/kg_gen.py", line 276, in generate
    graph = self.deduplicate(graph, method=deduplication_method, context=context)
File ".../kg_gen/steps/_3_deduplicate.py", line 28, in run_deduplication
    deduplicated_graph = run_semhash_deduplication(graph, semhash_similarity_threshold)
File ".../kg_gen/utils/deduplicate.py", line 72, in deduplicate
    self.duplicate_items = len(deduplication_result.duplicates)
AttributeError: 'DeduplicationResult' object has no attribute 'duplicates'
```

The offending lines (`src/kg_gen/utils/deduplicate.py`):

```python
self.deduplicated_items = len(deduplication_result.selected)
self.duplicate_items = len(deduplication_result.duplicates)   # <- 0.3.x-only attribute
...
duplicates = deduplication_result.duplicates
for duplicate in duplicates:
    original = duplicate.record
    if duplicate.duplicates and ... :
        duplicate_value = duplicate.duplicates[0][0]
```

## Suggested fix

Either of:

1. **Pin the dependency** to the supported line (quick, no code change):
   ```toml
   # pyproject.toml
   "semhash>=0.3.2,<0.4",
   ```
   This resolves to semhash 0.3.3 and the default `generate()` path works.

2. **Port `deduplicate.py` to the semhash 0.4.x `DeduplicationResult` API**
   (in 0.4.x the result exposes e.g. `selected_with_duplicates` and related
   fields instead of `.selected` / `.duplicates`), then widen the pin again.

Option 1 is the minimal fix to unbreak fresh installs today; option 2 keeps you
on the latest semhash. Happy to send a PR for whichever you prefer.

## Note

A `uv.lock` is committed, so `uv` users may be insulated, but `pip install -e .`
users (per the README's "Install from this repository" instructions) get 0.4.1
and hit the crash.
